server:
  port: 8081

spring:
  application:
    name: course-service
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://103.13.231.22:8761/eureka